OnlineShopWebApp/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineShop.BL;
using OnlineShopWebApp.ViewsModels;
using System.Data;

namespace OnlineShopWebApp.Areas.Admin.Controllers
{
    [Area(Constants.AdminRoleName)]
    [Authorize(Roles = Constants.AdminRoleName)]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> rolesManager;

        public RoleController(RoleManager<IdentityRole> rolesManager)
        {
            this.rolesManager = rolesManager;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await rolesManager.Roles.ToArrayAsync();
            return View(roles.Select(x => new RoleViewModel { Name = x.Name}).ToList());
        }
        public async Task<IActionResult> DeleteAsync(string name)
        {
            var role = await rolesManager.FindByNameAsync(name);
            if( role != null)
            {
                await rolesManager.DeleteAsync(role);
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddAsync(RoleViewModel role)
        {
            var result = await rolesManager.CreateAsync(new IdentityRole(role.Name));
            if(result.Succeeded)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(role);
        }
    }
}

OnlineShopWebApp/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using AutoMapper;
using OnlineShopWebApp.ViewsModels;
using OnlineShopWebApp.Helpers;
using OnlineShop.BL.Interfaces;
using OnlineShop.BL.Domains;
using OnlineShop.BL;

namespace OnlineShopWebApp.Areas.Admin.Controllers;

[Area(Constants.AdminRoleName)]
[Authorize(Roles = Constants.AdminRoleName)]
public class UserController : Controller
{
    private readonly IUsersServices usersServices;
    private readonly IRolesServices rolesServices;
    private readonly ImagesProvider imagesProvider;
    private readonly IMapper mapper;

    public UserController(IUsersServices usersServices, IRolesServices rolesServices, ImagesProvider imagesProvider, IMapper mapper)
    {
        this.usersServices = usersServices;
        this.rolesServices = rolesServices;
        this.imagesProvider = imagesProvider;
        this.mapper = mapper;
    }

    public async Task<IActionResult> Index()
    {
        var users = await usersServices.GetAllAsync();
        return View(users.Select(user => mapper.Map<UserViewModel>(user)).ToArray());
    }
    public async Task<IActionResult> DetailsAsync(string email)
    {
        var user = await usersServices.FindByEmailAsync(email);
        var userVM = mapper.Map<UserViewModel>(user);
        return View(userVM);
    }

    public IActionResult ChangePassword(string email)
    {
        var changePassword = new ChangePasswordViewModel()
        {
            Email = email
        };
        return View(changePassword);
    }

    [HttpPost]
    public async Task<IActionResult> ChangePasswordAsync(ChangePasswordViewModel changePasswordVM)
    {
        if (changePasswordVM.Email == changePasswordVM.Password)
        {
            ModelState.AddModelError("", "Логин и пароль не должны совпадать");
        }
        if (! ModelState.IsValid)
            return View(changePasswordVM);

        var changePassword = mapper.Map<ChangePassword>(changePasswordVM);
        await usersServices.ChangePasswordAsync(changePassword);

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> EditDataAsync(string email)
    {
        var user = await usersServices.FindByEmailAsync(email);

        if (user == null)
            return RedirectToAction(nameof(Index));

        var editUser = mapper.Map<EditUserViewModel>(user);
        return View(editUser);
    }

    [HttpPost]
    public async Task<IActionResult> EditDataAsync(EditUserViewModel editUserViewModel)
    {
        if (editUserViewModel == null)
            return RedirectToAction(nameof(Index));

        if (editUserViewModel.UploadFile != null)
        {
            var imagesPath = imagesProvider.SafeFiles(editUserViewModel.Email.Replace('@', '_'), editUserViewModel.UploadFile, ImageFolders.Profiles);
            editUserViewModel.ImagePath = imagesPath;
        }

        var user = mapper.Map<User>(editUserViewModel);
        await usersServices.EditDataAsync(user);

        var userVM = mapper.Map<UserViewModel>(user);
        return View("Details", userVM);
    }


    public async Task<IActionResult> EditRolesAsync(string email)
    {
        var user = await usersServices.FindByEmailAsync(email);
        IEnumerable<string> userRoles = await usersServices.GetRolesAsync(email);
        IEnumerable<Role> roles = rolesServices.GetAllRoles();

        var model = new EditRolesViewModel
        {
            Email = user.Email,
            UserRoles = userRoles.Select(x => new RoleViewModel { Name = x }).ToList(),
            AllRoles = roles.Select(x => new RoleViewModel { Name = x.Name }).ToList()
        };
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> EditRolesAsync(string email, Dictionary<string, bool> userRolesViewModel)
    {
        IEnumerable<string> userSelectedRoles = userRolesViewModel.Select(x => x.Key).ToArray();

        await usersServices.SetNewRolesAsync(email, userSelectedRoles);

        return Redirect($"/Admin/User/Details?email={email}");
    }

    public async Task<IActionResult> DeleteAsync(string email)
    {
        await usersServices.DeleteAsync(email);
        return RedirectToAction(nameof(Index));
    }
}

OnlineShopWebApp/Controllers/OrderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.BL;
using OnlineShop.Db;
using OnlineShop.Db.Entities;
using OnlineShop.Db.Interfaces;
using OnlineShopWebApp.ViewsModels;
using Constants = OnlineShop.BL.Constants;

namespace OnlineShopWebApp.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ICartsRepository cartsRepository;
        private readonly IOrdersRepository ordersRepository;
        private readonly IMapper mapper;
        public OrderController(ICartsRepository cartsRepository, IOrdersRepository ordersRepository, IMapper mapper)
        {
            this.cartsRepository = cartsRepository;
            this.ordersRepository = ordersRepository;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var cart = await cartsRepository.TryGetByLoginAsync(Constants.UserId);
            if (cart != null)
            {
                ViewBag.Cart = mapper.Map<CartViewModel>(cart);
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BuyAsync(UserDeliveryInfoViewModel userInfo)
        {
            if(ModelState.IsValid)
            {
                var cartDb = await cartsRepository.TryGetByLoginAsync(Constants.UserId);
                var order = new OrderEntity
                {
                    UserInfo = mapper.Map<UserDeliveryInfoEntity>(userInfo),
                    Items = cartDb.Items
                };

                await ordersRepository.AddAsync(order);
                await cartsRepository.ClearAsync(Constants.UserId);
                return View();
            }
            return View(nameof(Index), userInfo);
        }
    }
}

OnlineShopWebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

using AutoMapper;
using OnlineShop.BL.Interfaces;
using OnlineShopWebApp.ViewsModels;

namespace OnlineShopWebApp.Controllers;

public class ProductController : Controller
{
    private readonly IProductsServices productsServicies;
    private readonly IMapper mapper;

    public ProductController(IProductsServices productsServicies, IMapper mapper)
    {
        this.productsServicies = productsServicies;
        this.mapper = mapper;
    }

    public async Task<IActionResult> Index(Guid id)
    {
        var product = await productsServicies.TryGetByIdAsync(id);
        if (product == null)
            return RedirectToAction("Index", "Home");

        var model = mapper.Map<ProductViewModel>(product);
        return View(model);
    }
}

OnlineShopWebApp/Views/Shared/Components/Avatar/AvatarViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.BL.Interfaces;
using OnlineShopWebApp.ViewsModels;

namespace OnlineShopWebApp.Views.Shared.Components.Cart;

	public class AvatarViewComponent : ViewComponent
{
    private readonly IUsersServices usersServices;
    private readonly IMapper mapper;

    public AvatarViewComponent(IUsersServices usersServices, IMapper mapper)
    {
        this.usersServices = usersServices;
        this.mapper = mapper;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        if (User.Identity.IsAuthenticated)
        {
            var email = User.Identity.Name;
            var user = await usersServices.FindByEmailAsync(email);
            if(user != null)
            {
                var userVM = mapper.Map<UserViewModel>(user);
                return View("Avatar" , userVM);
            }
        }
        return View();
    }
}

OnlineShopWebApp/Views/Shared/Components/Cart/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.BL.Interfaces;

namespace OnlineShopWebApp.Views.Shared.Components.Cart;

public class CartViewComponent : ViewComponent
{
    private readonly ICartsServices cartsServices;

    public CartViewComponent(ICartsServices cartsServices)
    {
        this.cartsServices = cartsServices;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var cart = await cartsServices.TryGetByLoginAsync(User.Identity.Name);
        int сount = cart?.Items?.Count() ?? 0;
        return View("Cart", сount);
    }
}

OnlineShopWebApp/Views/Shared/Components/Favorites/FavoritesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Interfaces;

namespace OnlineShopWebApp.Views.Shared.Components.Favorites;

public class FavoritesViewComponent : ViewComponent
{
    private readonly IFavoriteServices favoriteServices;

    public FavoritesViewComponent(IFavoriteServices favoriteServices)
    {
        this.favoriteServices = favoriteServices;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var favoritesProduct = await favoriteServices.GetAllAsync(User.Identity.Name);
        int productCount = favoritesProduct?.Count() ?? 0;

        return View("Favorites", productCount);
    }
}

OnlineShopWebApp/Areas/Admin/Views/Shared/AdminLeftMenu.cshtml
<ul class="list-group">
    <li class="list-group-item">
        <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file" aria-hidden="true"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
            Заказы
        </a>
    </li>
    <li class="list-group-item">
        <a class="nav-link" asp-area="Admin" asp-controller="User" asp-action="Index">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users" aria-hidden="true"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
            Пользователи
        </a>
    </li>
    <li class="list-group-item">
        <a class="nav-link" asp-area="Admin" asp-controller="Role" asp-action="Index">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-person-gear" viewBox="0 0 16 16">
                <path d="M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm.256 7a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Zm3.63-4.54c.18-.613 1.048-.613 1.229 0l.043.148a.64.64 0 0 0 .921.382l.136-.074c.561-.306 1.175.308.87.869l-.075.136a.64.64 0 0 0 .382.92l.149.045c.612.18.612 1.048 0 1.229l-.15.043a.64.64 0 0 0-.38.921l.074.136c.305.561-.309 1.175-.87.87l-.136-.075a.64.64 0 0 0-.92.382l-.045.149c-.18.612-1.048.612-1.229 0l-.043-.15a.64.64 0 0 0-.921-.38l-.136.074c-.561.305-1.175-.309-.87-.87l.075-.136a.64.64 0 0 0-.382-.92l-.148-.045c-.613-.18-.613-1.048 0-1.229l.148-.043a.64.64 0 0 0 .382-.921l-.074-.136c-.306-.561.308-1.175.869-.87l.136.075a.64.64 0 0 0 .92-.382l.045-.148ZM14 12.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0Z" />
            </svg>
            Роли
        </a>
    </li>
    <li class="list-group-item">
        <a class="nav-link" asp-area="Admin" asp-controller="Product" asp-action="Index">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart" aria-hidden="true"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
            Продукты
        </a>
    </li>
</ul>